name: Bug report
description: "Found a bug? Please fill out the sections below."
type: bug
body:
  - type: textarea
    id: issue-summary
    attributes:
      label: Issue Summary
      description: A summary of the issue. This needs to be a clear detailed-rich summary.
    validations:
      required: true
  - type: textarea
    id: issue-expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: other-information
    attributes:
      label: Other information (incl. screenshots, branch, version, steps to reproduce,...)
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: Your Environment
      options:
        - Docker Compose setup
        - Local Poetry setup
        - Other